
-- Generated by ORDS REST Data Services 21.4.2.r0621806
-- Schema: ADMIN  Date: Mon May 23 05:55:45 2022 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ADMIN',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'admin',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.notes',
      p_base_path      => '/notes/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'search/:term',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'search/:term',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
    id, NOTE
FROM
    NOTES
    where upper(note) like ''%''||upper(:term)||''%''');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'create/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'create/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'insert into notes (notetype, note)
values (:notetype, :note)');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'delete/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'delete/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'delete from NOTES
where id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'getnote/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'getnote/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select note, notetype, id from notes
where id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'update/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.notes',
      p_pattern        => 'update/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'update NOTES
set note = :note,
notetype = :notetype
where id = :id');

    
        
COMMIT;

END;