/* Notes */

drop table notes;

CREATE TABLE "NOTES" 
   ("ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOTETYPE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"NOTE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "NOTES_PK" ON "NOTES" ("ID");

ALTER TABLE "NOTES" ADD CONSTRAINT "NOTES_PK" PRIMARY KEY ("ID") USING INDEX ENABLE;

commit;
