
-- Generated by ORDS REST Data Services 21.4.2.r0621806
-- Schema: ADMIN  Date: Fri Apr 29 04:57:58 2022 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ADMIN',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'admin',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.hr',
      p_base_path      => '/hr/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'A full set of REST APIs on the HR Sample Schema ready to be used in application development.');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'office/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Business Logic for creating or fetching office locations.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'office/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from office');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'office/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => 'API to create an office. You can pass in an address, region id and country id to use existing region and country.',
      p_source         => 
'declare

    l_error_out varchar2(4000);

BEGIN

    create_office  (:p_location_street_address,
                    :p_location_postal_code,
                    :p_location_city,
                    :p_location_state,
                    :p_country_id,
                    :p_country_name,
                    :p_region_id,
                    :p_region_name,
                    :p_location_id,
                    l_error_out);

    if l_error_out is not null then
        :return_message := l_error_out;
        :status_code := 400;
    end if;

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_location_street_address',
      p_bind_variable_name => 'p_location_street_address',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_location_postal_code',
      p_bind_variable_name => 'p_location_postal_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_country_name',
      p_bind_variable_name => 'p_country_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_location_state',
      p_bind_variable_name => 'p_location_state',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_region_name',
      p_bind_variable_name => 'p_region_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_location_city',
      p_bind_variable_name => 'p_location_city',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_country_id',
      p_bind_variable_name => 'p_country_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_region_id',
      p_bind_variable_name => 'p_region_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/',
      p_method             => 'POST',
      p_name               => 'p_location_id',
      p_bind_variable_name => 'p_location_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete a location by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    locations_tapi.del (:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/:id',
      p_method             => 'DELETE',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from locations where location_id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete a region by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    REGIONS_tapi.del(:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/:id',
      p_method             => 'DELETE',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from regions where region_id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete an employee by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    EMPLOYEES_tapi.del(:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from employees where EMPLOYEE_ID = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all regions.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    REGIONS_tapi.ins (:p_region_name);
    
    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'POST',
      p_name               => 'p_region_name',
      p_bind_variable_name => 'p_region_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from regions');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'regions/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    REGIONS_tapi.upd (:p_region_id, :p_region_name);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'PUT',
      p_name               => 'p_region_name',
      p_bind_variable_name => 'p_region_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'PUT',
      p_name               => 'p_region_id',
      p_bind_variable_name => 'p_region_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'regions/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all employees.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from employees');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    EMPLOYEES_tapi.ins(:p_job_id, :p_salary, :p_hire_date,
                       :p_department_id, :p_last_name, :p_email, :p_phone_number,
                       :p_first_name, :p_commission_pct, :p_manager_id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_salary',
      p_bind_variable_name => 'p_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_manager_id',
      p_bind_variable_name => 'p_manager_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_last_name',
      p_bind_variable_name => 'p_last_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_phone_number',
      p_bind_variable_name => 'p_phone_number',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_job_id',
      p_bind_variable_name => 'p_job_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_hire_date',
      p_bind_variable_name => 'p_hire_date',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_first_name',
      p_bind_variable_name => 'p_first_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_commission_pct',
      p_bind_variable_name => 'p_commission_pct',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_department_id',
      p_bind_variable_name => 'p_department_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'POST',
      p_name               => 'p_email',
      p_bind_variable_name => 'p_email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'employee/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
    EMPLOYEES_tapi.upd(:p_job_id, :p_employee_id, :p_salary, :p_hire_date,
                       :p_department_id, :p_last_name, :p_email, :p_phone_number,
                       :p_first_name, :p_commission_pct, :p_manager_id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_employee_id',
      p_bind_variable_name => 'p_employee_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_department_id',
      p_bind_variable_name => 'p_department_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_last_name',
      p_bind_variable_name => 'p_last_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_email',
      p_bind_variable_name => 'p_email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_phone_number',
      p_bind_variable_name => 'p_phone_number',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_job_id',
      p_bind_variable_name => 'p_job_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_hire_date',
      p_bind_variable_name => 'p_hire_date',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_first_name',
      p_bind_variable_name => 'p_first_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_commission_pct',
      p_bind_variable_name => 'p_commission_pct',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_manager_id',
      p_bind_variable_name => 'p_manager_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'employee/',
      p_method             => 'PUT',
      p_name               => 'p_salary',
      p_bind_variable_name => 'p_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all departments.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from departments');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    departments_tapi.ins(:p_department_name, :p_location_id, 
                         :p_manager_id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'POST',
      p_name               => 'p_department_name',
      p_bind_variable_name => 'p_department_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'POST',
      p_name               => 'p_location_id',
      p_bind_variable_name => 'p_location_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'POST',
      p_name               => 'p_manager_id',
      p_bind_variable_name => 'p_manager_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    departments_tapi.upd(:p_department_name, :p_department_id, :p_location_id, 
                         :p_manager_id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'p_department_name',
      p_bind_variable_name => 'p_department_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'p_location_id',
      p_bind_variable_name => 'p_location_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'p_manager_id',
      p_bind_variable_name => 'p_manager_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/',
      p_method             => 'PUT',
      p_name               => 'p_department_id',
      p_bind_variable_name => 'p_department_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all countries.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from countries');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    COUNTRIES_tapi.upd(:p_region_id, :p_country_id, :p_country_name);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'PUT',
      p_name               => 'p_region_id',
      p_bind_variable_name => 'p_region_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'PUT',
      p_name               => 'p_country_id',
      p_bind_variable_name => 'p_country_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'PUT',
      p_name               => 'p_country_name',
      p_bind_variable_name => 'p_country_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    COUNTRIES_tapi.ins(:p_region_id, :p_country_id, :p_country_name);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'POST',
      p_name               => 'p_country_id',
      p_bind_variable_name => 'p_country_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'POST',
      p_name               => 'p_region_id',
      p_bind_variable_name => 'p_region_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'POST',
      p_name               => 'p_country_name',
      p_bind_variable_name => 'p_country_name',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete a country by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    COUNTRIES_tapi.del (:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/:id',
      p_method             => 'DELETE',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'countries/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from countries where country_id = :id');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'countries/:id',
      p_method             => 'GET',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete a department by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from departments where department_id = :id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'departments/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    departments_tapi.del (:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/:id',
      p_method             => 'DELETE',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'departments/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all locations.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    locations_tapi.ins(:p_country_id, :p_city, :p_postal_code, :p_state_province,
                       :p_street_address);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'p_country_id',
      p_bind_variable_name => 'p_country_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'p_city',
      p_bind_variable_name => 'p_city',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'p_street_address',
      p_bind_variable_name => 'p_street_address',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'p_postal_code',
      p_bind_variable_name => 'p_postal_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'p_state_province',
      p_bind_variable_name => 'p_state_province',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    locations_tapi.upd(:p_country_id, :p_city, :p_postal_code, :p_state_province,
                       :p_location_id, :p_street_address);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_state_province',
      p_bind_variable_name => 'p_state_province',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_city',
      p_bind_variable_name => 'p_city',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_postal_code',
      p_bind_variable_name => 'p_postal_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_country_id',
      p_bind_variable_name => 'p_country_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_location_id',
      p_bind_variable_name => 'p_location_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'locations/',
      p_method             => 'PUT',
      p_name               => 'p_street_address',
      p_bind_variable_name => 'p_street_address',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'locations/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from locations');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get or delete a job by id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from jobs where job_id = :id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    jobs_tapi.del (:id);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/:id',
      p_method             => 'DELETE',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/:id',
      p_method             => 'DELETE',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/:id',
      p_method             => 'DELETE',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Create, Update or get all jobs.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from jobs');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    jobs_tapi.ins(:p_job_id, :p_min_salary, :p_job_title, :p_max_salary);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'p_job_id',
      p_bind_variable_name => 'p_job_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'p_min_salary',
      p_bind_variable_name => 'p_min_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'p_job_title',
      p_bind_variable_name => 'p_job_title',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'POST',
      p_name               => 'p_max_salary',
      p_bind_variable_name => 'p_max_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'jobs/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN

    jobs_tapi.upd(:p_job_id, :p_min_salary, :p_job_title, :p_max_salary);

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'p_job_id',
      p_bind_variable_name => 'p_job_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'p_max_salary',
      p_bind_variable_name => 'p_max_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'p_job_title',
      p_bind_variable_name => 'p_job_title',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'jobs/',
      p_method             => 'PUT',
      p_name               => 'p_min_salary',
      p_bind_variable_name => 'p_min_salary',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'salary/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Check to see if a salary is in the salary band for a specific job id.');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'salary/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => 'Check to see if a salary is in the salary band for a specific job id.',
      p_source         => 
'declare

l_message_out varchar2(4000);
l_error_out varchar2(4000);

BEGIN

    salary_check (:p_job_id,
                  :p_salary, 
                  l_message_out,
                  l_error_out);

:message_out := l_message_out;

    if l_error_out is not null then
        :return_message := l_error_out;
        :status_code := 400;
    end if;

    EXCEPTION
        WHEN NO_DATA_FOUND
        THEN
            :return_message := ''No Data Found'';
            :status_code := 400;
        WHEN VALUE_ERROR
        THEN
            :return_message := ''Please check your input values'';
            :status_code := 400;
        WHEN OTHERS
        THEN
            :return_message := ''Oracle Error: '' || SQLERRM;
            :status_code := 400;

END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'salary/',
      p_method             => 'GET',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'salary/',
      p_method             => 'GET',
      p_name               => 'p_job_id',
      p_bind_variable_name => 'p_job_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'salary/',
      p_method             => 'GET',
      p_name               => 'p_salary',
      p_bind_variable_name => 'p_salary',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'salary/',
      p_method             => 'GET',
      p_name               => 'message_out',
      p_bind_variable_name => 'message_out',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'salary/',
      p_method             => 'GET',
      p_name               => 'return_message',
      p_bind_variable_name => 'return_message',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'office/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get an office location by ID');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.hr',
      p_pattern        => 'office/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from office where location_id = :id');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'com.oracle.hr',
      p_pattern            => 'office/:id',
      p_method             => 'GET',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;