## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
## Database Development Tools - btspendo

    title: "Red Bull Racing Data in Oracle REST Data Services Dashboards"
    stackDescription: "Red Bull Racing Data in Oracle REST Data Services Dashboards"
    schemaVersion: 1.0.0
    version: "20220420"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - release
      - region

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid

    variables:
      
      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visible: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visible: false


    outputs:

      dashboard_url:
        title: "Dashboard URL"
        displayText: "Dashboard URL"
        type: string
        visible: true

      adb_password:
        title: "ADB Password"
        displayText: "ADB Password"
        type: string
        visible: true
    