
-- Generated by ORDS REST Data Services 21.4.2.r0621806
-- Schema: ADMIN  Date: Tue Apr 19 09:44:24 2022 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'com.oracle.dbtools.dashboard.Red Bull Race Data',
      p_base_path      => '/sdw/dashboards/Red Bull Race Data/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => 'Red Bull Race Data');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'com.oracle.dbtools.dashboard.Red Bull Race Data',
      p_pattern        => 'dashboard_settings',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'com.oracle.dbtools.dashboard.Red Bull Race Data',
      p_pattern        => 'dashboard_settings',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
	''application/json'' AS CONTENT_TYPE,
	CONCAT( CONCAT( TO_CLOB( ''{
    "com.oracle.dbtools.dashboard": {
        "name": "Red Bull Race Data",
        "description": "Red Bull Race Data",
        "layout": {
            "gridOptions": {
                "column": 4
            },
            "widgets": [
                {
                    "views": [
                        {
                            "type": "chart"
                        },
                        {
                            "type": "grid"
                        }
                    ],
                    "itemOptions": {
                        "x": 2,
                        "y": 0,
                        "w": 2,
                        "h": 1
                    },
                    "chartName": "Top Drivers With the Most Wins"
                },
                {
                    "views": [
                        {
                            "type": "grid"
                        }
         ' || '           ],
                    "itemOptions": {
                    '' ), TO_CLOB( ''    "x": 2,
                        "y": 1,
                        "w": 2,
                        "h": 2
                    },
                    "chartName": "Fastest Laps in 2021"
                },
                {
                    "views": [
                        {
                            "type": "chart"
                        },
                        {
                            "type": "grid"
                        }
                    ],
                    "itemOptions": {
                        "x": 0,
                        "y": 2,
                        "w": 2,
                        "h": 1
                    },
                    "chartName": "Most Dangerous Races with Wet Weather"
                },
                {
                    "views": [
                        {
                            "type": "chart"
                        },
                    ' || '    {
                            "type": "grid"
                        }
           '' ) ), TO_CLOB( ''         ],
                    "itemOptions": {
                        "x": 1,
                        "y": 0,
                        "w": 1,
                        "h": 2
                    },
                    "chartName": "Fastest Pitstops"
                },
                {
                    "views": [
                        {
                            "type": "chart"
                        },
                        {
                            "type": "grid"
                        }
                    ],
                    "itemOptions": {
                        "x": 0,
                        "y": 0,
                        "w": 1,
                        "h": 2
                    },
                    "chartName": "Top 10 Fan Favorite Races"
                }
            ]
        }
    }
}'' ) ) AS BODY,
	''dashboard_settings.json'' AS FILE_NAME
FROM
	DUAL');

    
        
COMMIT;

END;